### ISSUE TITLE
Progress/django에서 이벤트 호출하기(aws람다 대체)

### ISSUE THREAD

**Issue by kgw012** [myejin/news_scrapper_Django#4]
### 참고문서

https://medium.com/@kevin.michael.horan/scheduling-tasks-in-django-with-the-advanced-python-scheduler-663f17e868e6

https://wangin9.tistory.com/entry/django-celery

**Comment by myejin** [comment]
아래쪽 링크는 셀러리 링크라 나중에 봐도 될것 같아요!

**Comment by myejin** [comment]
✔️ 로컬(뉴스기사 분류기 모델)쪽에서 `async_cron` 활용으로 변경
- 참고 : https://pypi.org/project/async-cron/
